In [1]:
#qutip is not currently a required dependency and I'm not sure it will become one.

from qutip import *
import numpy as np
import matplotlib.pyplot as plt

In [2]:
qvac=basis(5,0)
print(qvac)
qa=destroy(5)
qadag=create(5)
print(qa*qvac)
print(qadag*qvac)
print(qa.dag()*qvac)
qn=num(5)
print(qvac.dag()*qn*qvac)
print((qadag*qadag*qvac).unit().dag()*qn*(qadag*qadag*qvac).unit())

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[2.]]


In [3]:
expect(qn,qvac)

0.0

In [4]:
expect(qn,qadag*qadag*qvac)

4.000000000000001

In [5]:
qvac=basis(5,0)
qc=create(5)
qN=num(5)
qstates=[(qc**k * qvac).unit() for k in range(5)]
print(expect(qN,qstates))

[0. 1. 2. 3. 4.]


# HO Hamiltonian

$m=1$

$H=0.5(a^{+}a+1)$

In [6]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

qadag=create(2)
qa=destroy(2)
qn=num(2)

qham=(qadag*qa+0.5*qeye(2))
print(qham)
qham=(qn+0.5*qeye(2))
print(qham)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  1.5]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  1.5]]


In [7]:
qham=0.5*(qa*qadag+qadag*qa)
print(qham)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]


In [8]:
qadag=create(3)
qa=destroy(3)
qham=0.5*(qa*qadag+qadag*qa)
print(qham)

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[0.5 0.  0. ]
 [0.  1.5 0. ]
 [0.  0.  1. ]]


In [9]:
qadag=create(6)
qa=destroy(6)
qham=0.5*(qa*qadag+qadag*qa)
print(qham)

Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0.  0.  0. ]
 [0.  1.5 0.  0.  0.  0. ]
 [0.  0.  2.5 0.  0.  0. ]
 [0.  0.  0.  3.5 0.  0. ]
 [0.  0.  0.  0.  4.5 0. ]
 [0.  0.  0.  0.  0.  2.5]]


In [10]:
qadag=create(8)
0.0625*qadag*qadag*qadag*qadag*qadag*qadag

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [1.67705098 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         4.43705984 0.         0.         0.         0.
  0.         0.        ]]

# Comparing some terms to my methods

In [12]:
import sys
sys.path.append('../..')
from src.sympy_utilities import *

In [13]:
mat=convert_to_matrix(0.0625*adag**6,8,8)
print(mat)
qadag=create(8)
0.0625*qadag*qadag*qadag*qadag*qadag*qadag

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1.67705098312484 0 0 0 0 0 0 0]
 [0 4.43705983732471 0 0 0 0 0 0]]


Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [1.67705098 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         4.43705984 0.         0.         0.         0.
  0.         0.        ]]

In [14]:
mat=convert_to_matrix(0.0625*a**6,8,8)
print(mat)
qa=destroy(8)
0.0625*qa*qa*qa*qa*qa*qa

[[0 0 0 0 0 0 1.67705098312484 0]
 [0 0 0 0 0 0 0 4.43705983732471]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.         0.
  1.67705098 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         4.43705984]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]

In [15]:
mat=convert_to_matrix(0.0625*a**3*adag**2*a,8,8)
print(mat)
qa=destroy(8)
qadag=create(8)
0.0625*qa*qa*qa*qadag*qadag*qa

[[0 0 0.530330085889911 0 0 0 0 0]
 [0 0 0 1.83711730708738 0 0 0 0]
 [0 0 0 0 4.33012701892219 0 0 0]
 [0 0 0 0 0 8.38525491562421 0 0]
 [0 0 0 0 0 0 14.3777171345106 0]
 [0 0 0 0 0 0 0 22.6825924444275]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[ 0.          0.          0.53033009  0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          1.83711731  0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          4.33012702  0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          8.38525492
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
  14.37771713  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]]