In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

In [2]:
vac=basis(5,0)
print(vac)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [3]:
a=destroy(5)
adag=create(5)
print(a*vac)
print()
print(adag*vac)
print()
print(a.dag()*vac)
print()
print(adag*adag*vac)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]


In [4]:
n=num(5)
print(vac.dag()*n*vac)
print((adag*adag*vac).unit().dag()*n*(adag*adag*vac).unit())
print((adag*adag*vac).unit().dag()*n*(adag*adag*vac).unit())

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[2.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[2.]]


In [5]:
expect(n,vac)

0.0

In [6]:
expect(n,adag*adag*vac)

4.000000000000001

In [7]:
vac=basis(5,0)
c=create(5)
N=num(5)
states=[(c**k * vac).unit() for k in range(5)]
print(expect(N,states))

[0. 1. 2. 3. 4.]


# HO Hamiltonian

$m=1$

$H=0.5(a^{+}a+1)$

In [2]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

adag=create(2)
a=destroy(2)
n=num(2)

ham=(adag*a+0.5*qeye(2))
print(ham)
ham=(n+0.5*qeye(2))
print(ham)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  1.5]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  1.5]]


In [3]:
ham=0.5*(a*adag+adag*a)
print(ham)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]


In [6]:
adag=create(3)
a=destroy(3)
ham=0.5*(a*adag+adag*a)
print(ham)

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[0.5 0.  0. ]
 [0.  1.5 0. ]
 [0.  0.  1. ]]
